version: "3.8"
services:
  front-envoy:
    image: envoyproxy/envoy:v1.26.4
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --service-cluster front-proxy --file-flush-interval-msec 50
    ports:
      - "8000:8000"

  upstream-service:
    image: cakebakery/request-info:v1
    command: -pretty -logH -logB
