version: "3.8"
services:
  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    ports:
      - "8080:8080"
      - "8443:8443"
  upstream-service:
    image: renukafernando/request-info:latest
    command: -pretty -logH -logB
