version: "3.8"
services:
  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - choreo-connect-with-apim_default
  upstream-service:
    image: cakebakery/request-info:v1
    command: -pretty -logH -logB
    networks:
      - choreo-connect-with-apim_default

networks:
  choreo-connect-with-apim_default:
    external: true