[ballerina.http.accessLogConfig]
# Enable printing access logs on the Console. The default value is `false`.
console = true
# Specify the file path to save the access logs. This is optional.  
path = "testAccessLog.txt"

[ballerina.http.traceLogAdvancedConfig]
# Enable printing trace logs on the Console. The default value is `false`.
console = true
# Specify the file path to save the trace logs. This is optional.
path = "testTraceLog.txt"
# Specify the hostname and port of a socket service to publish the trace logs. These are optional.
# host = "localhost"
# port = 9090